//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallPostByTechBrij.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int LikeID { get; set; }
        public int LikeBy { get; set; }
        public int PostId { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
